# Generated by the protocol buffer compiler.  DO NOT EDIT!
import sys

sys.path.append('/opt/trend/ddei/lib64/protobuf-2.4.1-py2.6.egg/')

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='quarantine.proto',
  package='trend.cs.feedback',
  serialized_pb='\n\x10quarantine.proto\x12\x11trend.cs.feedback\"\x16\n\nQuarantine*\x08\x08\x64\x10\x80\x80\x80\x80\x02')




_QUARANTINE = descriptor.Descriptor(
  name='Quarantine',
  full_name='trend.cs.feedback.Quarantine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(100, 536870912), ],
  serialized_start=39,
  serialized_end=61,
)

DESCRIPTOR.message_types_by_name['Quarantine'] = _QUARANTINE

class Quarantine(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUARANTINE
  
  # @@protoc_insertion_point(class_scope:trend.cs.feedback.Quarantine)

# @@protoc_insertion_point(module_scope)
