# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='usandbox.proto',
  package='',
  serialized_pb='\n\x0eusandbox.proto\"\x94\x05\n\x11UsandboxBlacklist\x12\x0f\n\x07version\x18\x01 \x02(\r\x12\x14\n\x0cmalware_name\x18\x02 \x01(\t\x12\x13\n\x0b\x63\x61v_rule_id\x18\x03 \x03(\r\x12\x0c\n\x04sha1\x18\x04 \x02(\x0c\x12\x14\n\x0c\x61rchive_sha1\x18\x05 \x02(\x0c\x12\x14\n\x0c\x66ile_type_id\x18\x06 \x02(\r\x12\x18\n\x10\x66ile_sub_type_id\x18\x07 \x02(\r\x12\x18\n\x10\x61tse_eng_version\x18\x08 \x02(\t\x12\x18\n\x10\x61tse_ptn_version\x18\t \x02(\t\x12\x15\n\rusbox_version\x18\n \x02(\t\x12\x12\n\nsc_version\x18\x0b \x02(\t\x12\x15\n\rsample_rating\x18\x0c \x02(\r\x12:\n\x0fviolated_policy\x18\r \x03(\x0b\x32!.UsandboxBlacklist.ViolatedPolicy\x12\x35\n\nblack_list\x18\x0e \x03(\x0b\x32!.UsandboxBlacklist.BlackListEntry\x1a\x33\n\x0eViolatedPolicy\x12\x11\n\tpolicy_id\x18\x01 \x02(\r\x12\x0e\n\x06\x64\x65tail\x18\x02 \x02(\t\x1a\x39\n\x07Trigger\x12\x0c\n\x04type\x18\x01 \x02(\r\x12\r\n\x05sc_id\x18\x02 \x01(\r\x12\x11\n\twrs_score\x18\x03 \x01(\r\x1a\x95\x01\n\x0e\x42lackListEntry\x12\x0c\n\x04type\x18\x01 \x02(\r\x12\x0c\n\x04sha1\x18\x02 \x01(\x0c\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\n\n\x02ip\x18\x04 \x01(\t\x12\x0e\n\x06\x64omain\x18\x05 \x01(\t\x12\x11\n\tbl_rating\x18\x06 \x02(\r\x12+\n\x07trigger\x18\x07 \x03(\x0b\x32\x1a.UsandboxBlacklist.Trigger')




_USANDBOXBLACKLIST_VIOLATEDPOLICY = descriptor.Descriptor(
  name='ViolatedPolicy',
  full_name='UsandboxBlacklist.ViolatedPolicy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='policy_id', full_name='UsandboxBlacklist.ViolatedPolicy.policy_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='detail', full_name='UsandboxBlacklist.ViolatedPolicy.detail', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=417,
  serialized_end=468,
)

_USANDBOXBLACKLIST_TRIGGER = descriptor.Descriptor(
  name='Trigger',
  full_name='UsandboxBlacklist.Trigger',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='UsandboxBlacklist.Trigger.type', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sc_id', full_name='UsandboxBlacklist.Trigger.sc_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='wrs_score', full_name='UsandboxBlacklist.Trigger.wrs_score', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=470,
  serialized_end=527,
)

_USANDBOXBLACKLIST_BLACKLISTENTRY = descriptor.Descriptor(
  name='BlackListEntry',
  full_name='UsandboxBlacklist.BlackListEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='UsandboxBlacklist.BlackListEntry.type', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sha1', full_name='UsandboxBlacklist.BlackListEntry.sha1', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='url', full_name='UsandboxBlacklist.BlackListEntry.url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ip', full_name='UsandboxBlacklist.BlackListEntry.ip', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='domain', full_name='UsandboxBlacklist.BlackListEntry.domain', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bl_rating', full_name='UsandboxBlacklist.BlackListEntry.bl_rating', index=5,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='trigger', full_name='UsandboxBlacklist.BlackListEntry.trigger', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=530,
  serialized_end=679,
)

_USANDBOXBLACKLIST = descriptor.Descriptor(
  name='UsandboxBlacklist',
  full_name='UsandboxBlacklist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='version', full_name='UsandboxBlacklist.version', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='malware_name', full_name='UsandboxBlacklist.malware_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cav_rule_id', full_name='UsandboxBlacklist.cav_rule_id', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sha1', full_name='UsandboxBlacklist.sha1', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='archive_sha1', full_name='UsandboxBlacklist.archive_sha1', index=4,
      number=5, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='file_type_id', full_name='UsandboxBlacklist.file_type_id', index=5,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='file_sub_type_id', full_name='UsandboxBlacklist.file_sub_type_id', index=6,
      number=7, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='atse_eng_version', full_name='UsandboxBlacklist.atse_eng_version', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='atse_ptn_version', full_name='UsandboxBlacklist.atse_ptn_version', index=8,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='usbox_version', full_name='UsandboxBlacklist.usbox_version', index=9,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sc_version', full_name='UsandboxBlacklist.sc_version', index=10,
      number=11, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sample_rating', full_name='UsandboxBlacklist.sample_rating', index=11,
      number=12, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='violated_policy', full_name='UsandboxBlacklist.violated_policy', index=12,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='black_list', full_name='UsandboxBlacklist.black_list', index=13,
      number=14, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_USANDBOXBLACKLIST_VIOLATEDPOLICY, _USANDBOXBLACKLIST_TRIGGER, _USANDBOXBLACKLIST_BLACKLISTENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=19,
  serialized_end=679,
)

_USANDBOXBLACKLIST_VIOLATEDPOLICY.containing_type = _USANDBOXBLACKLIST;
_USANDBOXBLACKLIST_TRIGGER.containing_type = _USANDBOXBLACKLIST;
_USANDBOXBLACKLIST_BLACKLISTENTRY.fields_by_name['trigger'].message_type = _USANDBOXBLACKLIST_TRIGGER
_USANDBOXBLACKLIST_BLACKLISTENTRY.containing_type = _USANDBOXBLACKLIST;
_USANDBOXBLACKLIST.fields_by_name['violated_policy'].message_type = _USANDBOXBLACKLIST_VIOLATEDPOLICY
_USANDBOXBLACKLIST.fields_by_name['black_list'].message_type = _USANDBOXBLACKLIST_BLACKLISTENTRY
DESCRIPTOR.message_types_by_name['UsandboxBlacklist'] = _USANDBOXBLACKLIST

class UsandboxBlacklist(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class ViolatedPolicy(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _USANDBOXBLACKLIST_VIOLATEDPOLICY
    
    # @@protoc_insertion_point(class_scope:UsandboxBlacklist.ViolatedPolicy)
  
  class Trigger(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _USANDBOXBLACKLIST_TRIGGER
    
    # @@protoc_insertion_point(class_scope:UsandboxBlacklist.Trigger)
  
  class BlackListEntry(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _USANDBOXBLACKLIST_BLACKLISTENTRY
    
    # @@protoc_insertion_point(class_scope:UsandboxBlacklist.BlackListEntry)
  DESCRIPTOR = _USANDBOXBLACKLIST
  
  # @@protoc_insertion_point(class_scope:UsandboxBlacklist)

# @@protoc_insertion_point(module_scope)
