# Generated by the protocol buffer compiler.  DO NOT EDIT!

import sys

sys.path.append('/opt/trend/ddei/lib64/protobuf-2.4.1-py2.6.egg/')

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='VSAPI_001.proto',
  package='',
  serialized_pb='\n\x0fVSAPI_001.proto\"\xc9\x05\n\x11VsapiFeedBackInfo\x12/\n\tvirusinfo\x18\x01 \x03(\x0b\x32\x1c.VsapiFeedBackInfo.VirusInfo\x12/\n\tenginever\x18\x02 \x02(\x0b\x32\x1c.VsapiFeedBackInfo.EngineVer\x12\x10\n\x08\x66iletype\x18\x03 \x02(\r\x12\x13\n\x0b\x66ilesubtype\x18\x04 \x02(\r\x12\x10\n\x08\x66ilesize\x18\x05 \x02(\x04\x12\x10\n\x08\x66ilesha1\x18\x06 \x01(\x0c\x12\x14\n\x0c\x66ilefullpath\x18\x07 \x01(\t\x12\x11\n\tmodule_id\x18\x08 \x02(\r\x12\x13\n\x0bmaxsha1size\x18\t \x02(\x04\x12\x30\n\x08procinfo\x18\n \x01(\x0b\x32\x1e.VsapiFeedBackInfo.ProcessInfo\x1a\xf4\x01\n\tVirusInfo\x12\x15\n\rdetectionname\x18\x01 \x02(\t\x12\x13\n\x0bpatternname\x18\x02 \x02(\t\x12\x12\n\npatternver\x18\x03 \x02(\r\x12\x17\n\x0fleaderscriptvid\x18\x04 \x01(\r\x12\x12\n\nleadercrcs\x18\x05 \x01(\x0c\x12\x17\n\x0fmajorminorttype\x18\x06 \x01(\x0c\x12\x15\n\rnormalizetype\x18\x07 \x01(\t\x12\x18\n\x10normalizeversion\x18\x08 \x01(\t\x12\x16\n\x0e\x64\x65tectionclass\x18\t \x01(\r\x12\x18\n\x10needfeedbackfile\x18\n \x01(\r\x1a>\n\tEngineVer\x12\r\n\x05major\x18\x01 \x02(\r\x12\r\n\x05minor\x18\x02 \x02(\r\x12\x13\n\x0b\x62uildnumber\x18\x03 \x02(\r\x1a`\n\x0bProcessInfo\x12\x13\n\x0bprocimgsize\x18\x01 \x02(\x04\x12\x13\n\x0bprocimgsha1\x18\x02 \x01(\x0c\x12\x17\n\x0fprocimgfullpath\x18\x03 \x02(\t\x12\x0e\n\x06procid\x18\x04 \x02(\r')




_VSAPIFEEDBACKINFO_VIRUSINFO = descriptor.Descriptor(
  name='VirusInfo',
  full_name='VsapiFeedBackInfo.VirusInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='detectionname', full_name='VsapiFeedBackInfo.VirusInfo.detectionname', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='patternname', full_name='VsapiFeedBackInfo.VirusInfo.patternname', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='patternver', full_name='VsapiFeedBackInfo.VirusInfo.patternver', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='leaderscriptvid', full_name='VsapiFeedBackInfo.VirusInfo.leaderscriptvid', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='leadercrcs', full_name='VsapiFeedBackInfo.VirusInfo.leadercrcs', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='majorminorttype', full_name='VsapiFeedBackInfo.VirusInfo.majorminorttype', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='normalizetype', full_name='VsapiFeedBackInfo.VirusInfo.normalizetype', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='normalizeversion', full_name='VsapiFeedBackInfo.VirusInfo.normalizeversion', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='detectionclass', full_name='VsapiFeedBackInfo.VirusInfo.detectionclass', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='needfeedbackfile', full_name='VsapiFeedBackInfo.VirusInfo.needfeedbackfile', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=327,
  serialized_end=571,
)

_VSAPIFEEDBACKINFO_ENGINEVER = descriptor.Descriptor(
  name='EngineVer',
  full_name='VsapiFeedBackInfo.EngineVer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='major', full_name='VsapiFeedBackInfo.EngineVer.major', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='minor', full_name='VsapiFeedBackInfo.EngineVer.minor', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='buildnumber', full_name='VsapiFeedBackInfo.EngineVer.buildnumber', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=573,
  serialized_end=635,
)

_VSAPIFEEDBACKINFO_PROCESSINFO = descriptor.Descriptor(
  name='ProcessInfo',
  full_name='VsapiFeedBackInfo.ProcessInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='procimgsize', full_name='VsapiFeedBackInfo.ProcessInfo.procimgsize', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='procimgsha1', full_name='VsapiFeedBackInfo.ProcessInfo.procimgsha1', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='procimgfullpath', full_name='VsapiFeedBackInfo.ProcessInfo.procimgfullpath', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='procid', full_name='VsapiFeedBackInfo.ProcessInfo.procid', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=637,
  serialized_end=733,
)

_VSAPIFEEDBACKINFO = descriptor.Descriptor(
  name='VsapiFeedBackInfo',
  full_name='VsapiFeedBackInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='virusinfo', full_name='VsapiFeedBackInfo.virusinfo', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='enginever', full_name='VsapiFeedBackInfo.enginever', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='filetype', full_name='VsapiFeedBackInfo.filetype', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='filesubtype', full_name='VsapiFeedBackInfo.filesubtype', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='filesize', full_name='VsapiFeedBackInfo.filesize', index=4,
      number=5, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='filesha1', full_name='VsapiFeedBackInfo.filesha1', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='filefullpath', full_name='VsapiFeedBackInfo.filefullpath', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='module_id', full_name='VsapiFeedBackInfo.module_id', index=7,
      number=8, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='maxsha1size', full_name='VsapiFeedBackInfo.maxsha1size', index=8,
      number=9, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='procinfo', full_name='VsapiFeedBackInfo.procinfo', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_VSAPIFEEDBACKINFO_VIRUSINFO, _VSAPIFEEDBACKINFO_ENGINEVER, _VSAPIFEEDBACKINFO_PROCESSINFO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=20,
  serialized_end=733,
)

_VSAPIFEEDBACKINFO_VIRUSINFO.containing_type = _VSAPIFEEDBACKINFO;
_VSAPIFEEDBACKINFO_ENGINEVER.containing_type = _VSAPIFEEDBACKINFO;
_VSAPIFEEDBACKINFO_PROCESSINFO.containing_type = _VSAPIFEEDBACKINFO;
_VSAPIFEEDBACKINFO.fields_by_name['virusinfo'].message_type = _VSAPIFEEDBACKINFO_VIRUSINFO
_VSAPIFEEDBACKINFO.fields_by_name['enginever'].message_type = _VSAPIFEEDBACKINFO_ENGINEVER
_VSAPIFEEDBACKINFO.fields_by_name['procinfo'].message_type = _VSAPIFEEDBACKINFO_PROCESSINFO
DESCRIPTOR.message_types_by_name['VsapiFeedBackInfo'] = _VSAPIFEEDBACKINFO

class VsapiFeedBackInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class VirusInfo(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _VSAPIFEEDBACKINFO_VIRUSINFO
    
    # @@protoc_insertion_point(class_scope:VsapiFeedBackInfo.VirusInfo)
  
  class EngineVer(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _VSAPIFEEDBACKINFO_ENGINEVER
    
    # @@protoc_insertion_point(class_scope:VsapiFeedBackInfo.EngineVer)
  
  class ProcessInfo(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _VSAPIFEEDBACKINFO_PROCESSINFO
    
    # @@protoc_insertion_point(class_scope:VsapiFeedBackInfo.ProcessInfo)
  DESCRIPTOR = _VSAPIFEEDBACKINFO
  
  # @@protoc_insertion_point(class_scope:VsapiFeedBackInfo)

# @@protoc_insertion_point(module_scope)
